web: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT run:app
worker: celery -A celery_worker.celery_app worker --loglevel=info
beat: celery -A celery_worker.celery_app beat --loglevel=info
